# Generated by Django 2.1 on 2018-09-15 14:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='active',
        ),
    ]
