# Generated by Django 2.1 on 2018-09-15 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_video_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='dislikes_to',
            new_name='dislikes',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='likes_to',
            new_name='likes',
        ),
    ]
